MAN = \
	alist.h.3 \
	array.h.3 \
	error.h.3 \
	gune.h.3 \
	ht.h.3 \
	lists.h.3 \
	misc.h.3 \
	queue.h.3 \
	stack.h.3 \
	string.h.3 \
	types.h.3 \
	version.h.3 \

MLINKS = \
	alist.h.3	alist_create.3	\
	alist.h.3	alist_destroy.3	\
	alist.h.3	alist_insert.3	\
	alist.h.3	alist_insert_uniq.3	\
	alist.h.3	alist_lookup.3	\
	alist.h.3	alist_delete.3	\
	alist.h.3	alist_empty.3	\
	alist.h.3	alist_walk.3	\
	alist.h.3	alist_merge.3	\
	alist.h.3	alist_merge_uniq.3	\
	array.h.3	array_create.3	\
	array.h.3	array_destroy.3	\
	array.h.3	array_resize.3	\
	array.h.3	array_get_data.3	\
	array.h.3	array_set_data.3	\
	array.h.3	array_compact.3	\
	array.h.3	array_grow.3	\
	array.h.3	array_shrink.3	\
	array.h.3	array_add.3	\
	array.h.3	array_remove.3	\
	error.h.3	set_logfile.3	\
	error.h.3	log_entry.3	\
	ht.h.3	ht_create.3	\
	ht.h.3	ht_destroy.3	\
	ht.h.3	ht_insert.3	\
	ht.h.3	ht_insert_uniq.3	\
	ht.h.3	ht_lookup.3	\
	ht.h.3	ht_delete.3	\
	ht.h.3	ht_empty.3	\
	ht.h.3	ht_walk.3	\
	ht.h.3	ht_merge.3	\
	ht.h.3	ht_merge_uniq.3	\
	lists.h.3	sll_create.3	\
	lists.h.3	sll_destroy.3	\
	lists.h.3	sll_empty.3	\
	lists.h.3	sll_remove_head.3	\
	lists.h.3	sll_remove_next.3	\
	lists.h.3	sll_prepend_head.3	\
	lists.h.3	sll_append_head.3	\
	lists.h.3	sll_get_data.3	\
	lists.h.3	sll_set_data.3	\
	lists.h.3	sll_forward.3	\
	lists.h.3	sll_dump.3	\
	lists.h.3	sll_append.3	\
	lists.h.3	sll_prepend.3	\
	lists.h.3	dll_create.3	\
	lists.h.3	dll_destroy.3	\
	lists.h.3	dll_empty.3	\
	lists.h.3	dll_remove_head.3	\
	lists.h.3	dll_prepend_head.3	\
	lists.h.3	dll_append_head.3	\
	lists.h.3	dll_get_data.3	\
	lists.h.3	dll_set_data.3	\
	lists.h.3	dll_forward.3	\
	lists.h.3	dll_backward.3	\
	lists.h.3	dll_dump.3	\
	lists.h.3	dll_append.3	\
	lists.h.3	dll_prepend.3	\
	misc.h.3	ptr_eq.3	\
	misc.h.3	num_eq.3	\
	misc.h.3	posnum_eq.3	\
	misc.h.3	sym_eq.3	\
	queue.h.3	queue_create.3	\
	queue.h.3	queue_enqueue.3	\
	queue.h.3	queue_dequeue.3	\
	queue.h.3	queue_peek.3	\
	queue.h.3	queue_empty.3	\
	queue.h.3	queue_destroy.3	\
	queue.h.3	queue_append.3	\
	stack.h.3	stack_create.3	\
	stack.h.3	stack_pop.3	\
	stack.h.3	stack_peek.3	\
	stack.h.3	stack_push.3	\
	stack.h.3	stack_empty.3	\
	stack.h.3	stack_destroy.3	\
	string.h.3	str_eq.3	\

