MAN = \
	alist.h.3 \
	array.h.3 \
	error.h.3 \
	gune.h.3 \
	ht.h.3 \
	lists.h.3 \
	misc.h.3 \
	queue.h.3 \
	stack.h.3 \
	string.h.3 \
	types.h.3 \
	version.h.3 \

MKLINKS = \
	alist.h.3	alist_create	\
	alist.h.3	alist_destroy	\
	alist.h.3	alist_insert	\
	alist.h.3	alist_insert_uniq	\
	alist.h.3	alist_lookup	\
	alist.h.3	alist_delete	\
	alist.h.3	alist_empty	\
	alist.h.3	alist_walk	\
	alist.h.3	alist_merge	\
	alist.h.3	alist_merge_uniq	\
	array.h.3	array_create	\
	array.h.3	array_destroy	\
	array.h.3	array_resize	\
	array.h.3	array_get_data	\
	array.h.3	array_set_data	\
	array.h.3	array_compact	\
	array.h.3	array_grow	\
	array.h.3	array_shrink	\
	array.h.3	array_add	\
	array.h.3	array_remove	\
	error.h.3	set_logfile	\
	error.h.3	log_entry	\
	ht.h.3	ht_create	\
	ht.h.3	ht_destroy	\
	ht.h.3	ht_insert	\
	ht.h.3	ht_insert_uniq	\
	ht.h.3	ht_lookup	\
	ht.h.3	ht_delete	\
	ht.h.3	ht_empty	\
	ht.h.3	ht_walk	\
	ht.h.3	ht_merge	\
	ht.h.3	ht_merge_uniq	\
	lists.h.3	sll_create	\
	lists.h.3	sll_destroy	\
	lists.h.3	sll_empty	\
	lists.h.3	sll_remove_head	\
	lists.h.3	sll_remove_next	\
	lists.h.3	sll_prepend_head	\
	lists.h.3	sll_append_head	\
	lists.h.3	sll_get_data	\
	lists.h.3	sll_set_data	\
	lists.h.3	sll_forward	\
	lists.h.3	sll_dump	\
	lists.h.3	sll_append	\
	lists.h.3	sll_prepend	\
	lists.h.3	dll_create	\
	lists.h.3	dll_destroy	\
	lists.h.3	dll_empty	\
	lists.h.3	dll_remove_head	\
	lists.h.3	dll_prepend_head	\
	lists.h.3	dll_append_head	\
	lists.h.3	dll_get_data	\
	lists.h.3	dll_set_data	\
	lists.h.3	dll_forward	\
	lists.h.3	dll_backward	\
	lists.h.3	dll_dump	\
	lists.h.3	dll_append	\
	lists.h.3	dll_prepend	\
	misc.h.3	ptr_eq	\
	misc.h.3	num_eq	\
	misc.h.3	posnum_eq	\
	misc.h.3	sym_eq	\
	queue.h.3	queue_create	\
	queue.h.3	queue_enqueue	\
	queue.h.3	queue_dequeue	\
	queue.h.3	queue_peek	\
	queue.h.3	queue_empty	\
	queue.h.3	queue_destroy	\
	queue.h.3	queue_append	\
	stack.h.3	stack_create	\
	stack.h.3	stack_pop	\
	stack.h.3	stack_peek	\
	stack.h.3	stack_push	\
	stack.h.3	stack_empty	\
	stack.h.3	stack_destroy	\
	string.h.3	str_eq	\

